"""Phase 3, the abort gate: Game Summaries byte for byte against the goldens.

A summary that differs by one space is a failure, not a nit. The summary text
*is* the embedded text, so a divergence means the stored vector no longer
corresponds to its own source — and nothing anywhere errors.
"""

from __future__ import annotations

import re
from typing import Any

import pytest

from zeitnot.db import DB
from zeitnot.models import Game, GameSummaryData, MoveAnalysis, PhaseStats, Player
from zeitnot.summary import (
    classify_game_length,
    detect_pattern,
    extract_summary_data,
    generate_summary,
    weakest_phase,
)

pytestmark = [pytest.mark.corpus, pytest.mark.golden]

_ECO_URL_HEADER = re.compile(r'\[ECOUrl "([^"]*)"\]')


def _rebuild_game(row: dict[str, Any]) -> Game:
    """Reconstruct the ingestion-time Game from stored columns.

    Game.eco holds the Chess.com openings URL, which is not a column but is
    carried in the PGN as [ECOUrl "..."]. Recovering it there is what lets
    opening_name() run against stored data, and it is exactly what cmd/golden
    does on the Go side.
    """
    game = Game(
        uuid=row["uuid"],
        pgn=row["pgn"],
        time_class=row["time_class"],
        white=Player(username=row["white_username"], rating=row["white_rating"]),
        black=Player(username=row["black_username"], rating=row["black_rating"]),
    )
    match = _ECO_URL_HEADER.search(row["pgn"])
    if match:
        game.eco = match.group(1)

    if row["result"] == "white":
        game.white.result, game.black.result = "win", "lost"
    elif row["result"] == "black":
        game.white.result, game.black.result = "lost", "win"
    else:
        game.white.result, game.black.result = "draw", "draw"
    return game


@pytest.fixture(scope="module")
def regenerated(db: DB, corpus_username: str) -> dict[str, dict[str, Any]]:
    """Every stored game's summary, regenerated by the Python implementation."""
    with db.cursor() as cur:
        cur.execute(
            """SELECT g.uuid::text, g.pgn, g.result, g.time_class,
                      g.white_username, g.white_rating, g.black_username, g.black_rating
               FROM games g ORDER BY g.uuid"""
        )
        rows = cur.fetchall()

    out: dict[str, dict[str, Any]] = {}
    for row in rows:
        record = {
            "uuid": row[0],
            "pgn": row[1] or "",
            "result": row[2] or "",
            "time_class": row[3] or "",
            "white_username": row[4] or "",
            "white_rating": row[5] or 0,
            "black_username": row[6] or "",
            "black_rating": row[7] or 0,
        }
        moves = [
            MoveAnalysis(
                evaluation=m.evaluation,
                is_mate=m.is_mate,
                mate_in=m.mate_in,
                centipawn_loss=m.cpl,
                classification=m.classification,
                fen_before=m.fen_before,
            )
            for m in db.get_moves_for_game(row[0])
        ]
        data = extract_summary_data(_rebuild_game(record), moves, corpus_username)
        out[row[0]] = {"data": data, "text": generate_summary(data)}
    return out


def test_every_summary_matches_the_golden_byte_for_byte(
    summary_goldens: list[dict[str, Any]], regenerated: dict[str, dict[str, Any]]
) -> None:
    assert len(summary_goldens) == len(regenerated), "the corpus changed since the capture"

    mismatches = []
    for golden in summary_goldens:
        uuid = golden["game_uuid"]
        got = regenerated[uuid]["text"]
        if got != golden["text"]:
            mismatches.append(f"{uuid}\n  go:     {golden['text']!r}\n  python: {got!r}")
    assert not mismatches, "summary text diverged:\n" + "\n".join(mismatches)


def test_every_summary_matches_what_is_actually_stored(
    summary_goldens: list[dict[str, Any]], regenerated: dict[str, dict[str, Any]]
) -> None:
    """The stronger claim, and the one that protects the embeddings.

    Matching the golden proves Python agrees with Go. Matching `summary_text`
    proves both agree with the text the stored vectors were built from.
    """
    for golden in summary_goldens:
        stored = golden["stored_text"]
        if not stored:
            continue
        assert regenerated[golden["game_uuid"]]["text"] == stored


def test_every_summary_data_field_matches_the_golden(
    summary_goldens: list[dict[str, Any]], regenerated: dict[str, dict[str, Any]]
) -> None:
    """The intermediate struct, not only the rendered text.

    Two of its fields — biggest_swing and biggest_swing_move — never reach the
    summary string, so a bug in them would pass the byte comparison above while
    still being wrong.
    """
    field_map = {
        "Result": "result",
        "PlayerColor": "player_color",
        "TimeClass": "time_class",
        "OpeningName": "opening_name",
        "ECOCode": "eco_code",
        "TotalMoves": "total_moves",
        "BiggestSwing": "biggest_swing",
        "BiggestSwingMove": "biggest_swing_move",
        "WasWinning": "was_winning",
        "WasLosing": "was_losing",
        "TerminationType": "termination_type",
        "OpponentRating": "opponent_rating",
    }
    phase_map = {
        "Blunders": "blunders",
        "Mistakes": "mistakes",
        "Inaccuracies": "inaccuracies",
        "TotalCPL": "total_cpl",
        "MoveCount": "move_count",
    }

    for golden in summary_goldens:
        data: GameSummaryData = regenerated[golden["game_uuid"]]["data"]
        want = golden["data"]
        for go_name, py_name in field_map.items():
            assert getattr(data, py_name) == want[go_name], f"{golden['game_uuid']}: {py_name}"
        for go_phase, py_phase in (
            ("Opening", "opening"),
            ("Middlegame", "middlegame"),
            ("Endgame", "endgame"),
        ):
            phase: PhaseStats = getattr(data, py_phase)
            for go_name, py_name in phase_map.items():
                assert getattr(phase, py_name) == want[go_phase][go_name], (
                    f"{golden['game_uuid']}: {py_phase}.{py_name}"
                )


def test_the_remaining_preserved_defect_is_still_preserved(
    summary_goldens: list[dict[str, Any]],
) -> None:
    """A guard against someone "fixing" this incidentally.

    Recorded in docs/python-rewrite/00-plan.md as a Phase 8 item. Fixing it
    changes Game Summary text, so it needs its own change with its own
    verification rather than riding along with something else.
    """
    # Defect 1: "Endgame was weakest" is the tie catch-all. Still unreached on
    # the captured corpus — 0 of 74 — but reachable in principle.
    assert weakest_phase(PhaseStats(), PhaseStats(), PhaseStats()) == "Endgame was weakest", (
        "an all-zero tie must still report the endgame; preserved defect 1 has been fixed"
    )

    # Defect 2 (a drawn game summarized as a loss) was FIXED on 2026-08-31.
    # The goldens predate that fix, so they still carry the old text — which is
    # why this asserts the golden's staleness rather than the code's behavior.
    # Live coverage of the fix is in tests/test_summary.py, which runs
    # everywhere; this file skips without a database and captured goldens.
    verdicts = {g["data"]["Result"] for g in summary_goldens}
    assert "drew" not in verdicts, (
        "the goldens now contain 'drew', so they have been recaptured since the "
        "draw fix — update this test and testdata/golden/MANIFEST.md together"
    )


@pytest.mark.parametrize(
    ("total_moves", "want"),
    [
        (0, "Short game"),
        (19, "Short game"),
        (20, "Medium length game"),
        (39, "Medium length game"),
        (40, "Long game"),
        (200, "Long game"),
    ],
)
def test_classify_game_length_boundaries(total_moves: int, want: str) -> None:
    assert classify_game_length(total_moves) == want


@pytest.mark.parametrize(
    ("result", "was_winning", "was_losing", "want"),
    [
        ("won", False, True, "Came back from losing position"),
        ("won", True, True, "Came back from losing position"),
        ("won", True, False, "Steady advantage throughout"),
        ("won", False, False, "Converted a close game"),
        ("lost", True, False, "Threw a winning position"),
        ("lost", True, True, "Threw a winning position"),
        ("lost", False, True, "Was outplayed"),
        ("lost", False, False, "Lost a close game"),
        # The four dead verdicts. Ported and tested so the Phase 8 fix that
        # makes them live is a one-line change with a suite already in place.
        ("drew", True, False, "Missed winning opportunity"),
        ("drew", False, True, "Saved a draw from worse position"),
        ("drew", True, True, "Wild game ended in draw"),
        ("drew", False, False, "Even game throughout"),
        ("something else", False, False, "Unknown pattern"),
    ],
)
def test_detect_pattern_matrix(result: str, was_winning: bool, was_losing: bool, want: str) -> None:
    data = GameSummaryData(result=result, was_winning=was_winning, was_losing=was_losing)
    assert detect_pattern(data) == want


def test_weakest_phase_picks_the_highest_average_not_the_highest_total() -> None:
    """Averages, not totals — a long clean endgame must not outrank a short
    sloppy opening."""
    opening = PhaseStats(total_cpl=300, move_count=3)  # avg 100
    middlegame = PhaseStats(total_cpl=150, move_count=15)  # avg 10
    endgame = PhaseStats(total_cpl=400, move_count=40)  # avg 10, highest total
    assert weakest_phase(opening, middlegame, endgame) == "Opening was weakest"
    assert weakest_phase(PhaseStats(), middlegame, PhaseStats()) == "Middlegame was weakest"
